# Day 3 - Exercise 1

Imports and function definitions

In [1]:
import numpy as np

def id(x):
    '''Be careful. Using NumPy internals. Can change with any version.'''
    return x.__array_interface__['data'][0]

# 1a)

In [2]:
null_vec = np.zeros((10))
null_vec[4] = 5
null_vec

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

# 1b)

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 1c)

In [4]:
a = np.arange(10,50)
print('Initial vector:\n', a)
print('\nReversed vector:\n', a[::-1])

Initial vector:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reversed vector:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 1d)

In [5]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 1e)

In [6]:
a = np.array([1, 2, 0, 0, 4, 0])
print('Array\n', a)
print('has non zero elements at positions\n', np.where(a != 0)[0])

Array
 [1 2 0 0 4 0]
has non zero elements at positions
 [0 1 4]


# 1f)

In [7]:
a = np.random.rand((30))
print('Mean value of random vector\n', a)
print('reads\n', np.mean(a))

Mean value of random vector
 [0.93237551 0.51106681 0.21188348 0.67327996 0.99593277 0.48110574
 0.74235026 0.52104853 0.56417847 0.2290752  0.38305533 0.8488502
 0.36827591 0.7414156  0.47538997 0.3667223  0.5921126  0.19592902
 0.64805212 0.61239882 0.56868537 0.6037067  0.25595999 0.04856384
 0.96773239 0.5138895  0.51774777 0.40825473 0.55003368 0.17885773]
reads
 0.5235976776931468


# 1g)

In [8]:
a = np.ones((6,6))
a[1:a.shape[0]-1,1:a.shape[1]-1] = 0
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

# 1h)

In [9]:
a = np.ones((8,8))
a[::2][:,1::2] = 0
a[1::2][:,::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# 1i)

In [10]:
np.tile(np.identity(2),(4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# 1j)

In [11]:
Z = np.arange(11)
print('ID before in-place operation:\t', id(Z))
Z[np.logical_and(Z > 3, Z < 8)] *= -1
print('ID after in-place operation:\t', id(Z))
Z

ID before in-place operation:	 93909964050400
ID after in-place operation:	 93909964050400


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

# 1k)

In [12]:
Z = np.random.random(10)
Z = np.sort(Z)
Z

array([0.18988229, 0.34529463, 0.44246893, 0.52420758, 0.54584726,
       0.56861557, 0.57767626, 0.77074828, 0.8063234 , 0.83470982])

# 1l)

In [13]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = A == B
equal

array([False, False,  True,  True,  True])

# 1m)

In [14]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
print('ID before in-place operation:\t', id(Z))

Z = Z.view(np.float32)

print(Z.dtype)
print('ID after in-place operation:\t', id(Z))

int32
ID before in-place operation:	 93909971523872
float32
ID after in-place operation:	 93909971523872


# 1n)

In [15]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print(D)

[ 18  66 132]
